### ISSUE TITLE
Since a while I get this error

### ISSUE THREAD

**Issue by francesco2013** [danger89/metacritic_api#1]
It used to work very fine then all of a sudden:

PHP Fatal error:  Call to a member function find() on boolean in /var/www/playstationweb/html/classes/metacritic/metacritic_api-master/metacritic.php on line 45

Can you please tell me how to fix it please ?

Thanks dude

Francesco

**Comment by danger89** [comment]
Hi, 

I don't have time today... **maybe somewhere this week**. Nevertheless the problem is in this line of code:
 `foreach($html->find('div[class=product_title] span[itemprop=name]') as $element) `

What it says is the function find() above, is called on $html, which is a boolean. At least at this moment. $html is set some line higher:
`$html = str_get_html($page_response);`
Could it be that the page you/app queries doesn't exist? I mean looking into the implemenation of this str_get_html() function, the function can return a boolean (false), if the $page_response is empty:
```
    if (empty($str) || strlen($str) > MAX_FILE_SIZE)
	{
		$dom->clear();
		return false;
	}

```
_Off-topic_; apparently I also need to do (I read somewhere):
$html->clear();

**Comment by francesco2013** [comment]
Thanks man :) I am going to check out my code too !

2016-03-25 17:57 GMT+01:00 Melroy van den Berg <notifications@github.com>:

**Comment by francesco2013** [comment]
Can it be the html of metacritic changed ?

2016-03-26 10:38 GMT+01:00 Francesco fazio <ffazio1@gmail.com>:

**Comment by danger89** [comment]
Sure it can! Let me take a look as well.

**Comment by francesco2013** [comment]
thanks mate :)

2016-03-27 13:09 GMT+02:00 Melroy van den Berg <notifications@github.com>:

**Comment by danger89** [comment]
OK, what I did so far:
 - Using the latest Unirest API
 - Adding JSON error output when the page couldn't be loaded/parsed (see [README](https://github.com/danger89/metacritic_api/blob/master/README.md) )
 - Creating a tagged version from the latest master: [v1.0](https://github.com/danger89/metacritic_api/tree/v1.0) ! 
 - I changed the API calls, it was useless to parse the 'response' to the next function. It now uses a local variable to store the body response. Please, check-out the [example page](https://github.com/danger89/metacritic_api/blob/master/example.php) how to call it now...

If it's still not working, may I ask which game you try to fetch from Metacritic? Specifically which for game title are you searching? Thanks.

**Comment by francesco2013** [comment]
I have no words to tell you how thankful i am mate :) works like a charm !

**Comment by francesco2013** [comment]
Hey man I think they did something again and I always get the error Page
cannot be loaded from your script :(

2016-03-28 6:12 GMT+02:00 Francesco fazio <ffazio1@gmail.com>:

**Comment by francesco2013** [comment]
never mind it was my mistake sorry man and thanks a million again !

2016-04-01 13:24 GMT+02:00 Francesco fazio <ffazio1@gmail.com>:

**Comment by danger89** [comment]
you are welcome.
